### ISSUE TITLE
Is this package still maintained?

### ISSUE THREAD

**Issue by enilsen16** [oarrabi/zenixir#5]
Hey @oarrabi - Just wondering what the status of this package is. I spent some time this week upgrading this to use HTTPoison over HTTPotion. As well as a few other fixes and eventually I want to remove Dicts in favor of Maps.

It also would be great if this package was pushed to Hex.pm and had the docs uploaded as well. You clearly spent a lot of time with this package. I am also fine with just continuing my fork. Thanks!

**Comment by nsomar** [comment]
Hey @enilsen16 

Thanks for contacting me and sorry for the late reply,
Would you be able to provide a PR with your changes?

Also I am looking for co-authors and maintainers. Would you be up to become a maintainer of the project?

**Comment by enilsen16** [comment]
Sure I am happy to help. 😄 

Are there any plans to have zendesk support this package officially (looks like you work there)?

**Comment by nsomar** [comment]
I don't think we do have it planned unfortunately, I would love to have it too :) (cc @mathewcropper)

**Comment by enilsen16** [comment]
I made a PR with the changes that I have from about a month ago.

**Comment by mathewcropper** [comment]
Thanks for the cc @oarrabi! Hey @enilsen16. I'm Mat, the product manager for our SDKs at Zendesk. 

At the moment our focus is elsewhere, so there are no plans to officially support Elixir right now. It is in the mix with other 'will you support my favourite language' feature requests, though, and I revisit this regularly to see whether the time is right to pick something like this up.

One thing I'm working on is adding a 'community projects' section to our SDK docs, aiming to give things like this greater visibility. I can't promise to work on an official Elixir SDK any time soon, but I certainly can give the project broader visibility if you're interested?

**Comment by enilsen16** [comment]
@oarrabi I'll keep making PRs if I need to.

**Comment by enilsen16** [comment]
Oh @mathewcropper I think that would be a good idea. Happy to help set that up in whatever capacity is needed. 😄

**Comment by mathewcropper** [comment]
Awesome. I'll keep you both posted!

**Comment by enilsen16** [comment]
@oarrabi Happy to help start maintaining Zenixir 😀
